steps:
  # Step 1: Ensure the model exists before building the image
  # If the model is missing, this runs the training script to generate it
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    timeout: '600s'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        if [ ! -f "models/neo_classifier.joblib" ]; then
          echo "Model not found. Running training pipeline..."
          python scripts/train.py
        else
          echo "Model found. Proceeding to build."
        fi

  # Step 2: Build the unified container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/asteroid-repo/unified-app:latest', 
      '.'
    ]

  # Step 3: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/asteroid-repo/unified-app:latest']

  # Step 4: Deploy the Backend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'asteroid-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/asteroid-repo/unified-app:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'

  # Step 5: Deploy the Frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'asteroid-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/asteroid-repo/unified-app:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--command'
      - 'streamlit'
      - '--args'
      - 'run,frontend/app.py,--server.port,8080,--server.address,0.0.0.0'
      - '--set-env-vars'
      - 'BACKEND_URL=https://asteroid-backend-617598390128.us-central1.run.app'

# Fixes the logging permissions issue for GitHub Actions
options:
  logging: CLOUD_LOGGING_ONLY

# Explicitly track the model as a build artifact
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild/models/'
    paths: ['models/neo_classifier.joblib']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/asteroid-repo/unified-app:latest'